TRUNCATE TABLE cipherguard.gpgkeys;
TRUNCATE TABLE cipherguard.groups;
TRUNCATE TABLE cipherguard.groups_users;
TRUNCATE TABLE cipherguard.permissions;
TRUNCATE TABLE cipherguard.profiles;
TRUNCATE TABLE cipherguard.resources;
TRUNCATE TABLE cipherguard.roles;
TRUNCATE TABLE cipherguard.secrets;
TRUNCATE TABLE cipherguard.users;
TRUNCATE TABLE cipherguard.folders;
TRUNCATE TABLE cipherguard.folders_relations;
TRUNCATE TABLE cipherguard.resource_types;
TRUNCATE TABLE cipherguard.actions;
TRUNCATE TABLE cipherguard.action_logs;
TRUNCATE TABLE cipherguard.entities_history;
TRUNCATE TABLE cipherguard.permissions_history;
TRUNCATE TABLE cipherguard.secret_accesses;
TRUNCATE TABLE cipherguard.secrets_history;
TRUNCATE TABLE cipherguard.phinxlog;
TRUNCATE TABLE cipherguard.tags;
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_gpgkeys.txt' INTO TABLE cipherguard.gpgkeys FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_groups.txt' INTO TABLE cipherguard.groups FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_groups_users.txt' INTO TABLE cipherguard.groups_users FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_permissions.txt' INTO TABLE cipherguard.permissions FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_profiles.txt' INTO TABLE cipherguard.profiles FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_resources.txt' INTO TABLE cipherguard.resources FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_roles.txt' INTO TABLE cipherguard.roles FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_secrets.txt' INTO TABLE cipherguard.secrets FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_users.txt' INTO TABLE cipherguard.users FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_folders.txt' INTO TABLE cipherguard.folders FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_folders_relations.txt' INTO TABLE cipherguard.folders_relations FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_resource_types.txt' INTO TABLE cipherguard.resource_types FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_actions.txt' INTO TABLE cipherguard.actions FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_action_logs.txt' INTO TABLE cipherguard.action_logs FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_entities_history.txt' INTO TABLE cipherguard.entities_history FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_permissions_history.txt' INTO TABLE cipherguard.permissions_history FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_secret_accesses.txt' INTO TABLE cipherguard.secret_accesses FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_secrets_history.txt' INTO TABLE cipherguard.secrets_history FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_phinxlog.txt' INTO TABLE cipherguard.phinxlog FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/var/lib/mysql-files/obfusc_dump_tags.txt' INTO TABLE cipherguard.tags FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
